spring:
  application:
    name: http-client-resttemplate

server:
  port: 8081

seal:
  spring:
    service-client:
      http:
        forward-metadata:
          - overlay-ns
#        default-channel-name: "default-channel-name"
        channels:
          http-server-resttemplate-channel:
            address: "http://127.0.0.1:8080"
        services:
          http-server-resttemplate:
            channel-name: http-server-resttemplate-channel