<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.seal90</groupId>
		<artifactId>service-client-spring-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>service-client-spring</artifactId>
	<name>service-client-spring</name>
	<description>service client</description>
	<packaging>pom</packaging>

	<modules>
		<module>service-client-carries-by-grpc</module>
		<module>service-client-carries-by-rsocket</module>
		<module>service-client-carries-http</module>
		<module>service-client-core</module>
		<module>service-client-grpc</module>
		<module>service-client-http</module>
<!--		<module>service-client-mqtt</module>-->
		<module>service-client-rsocket</module>
	</modules>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>