// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Message.proto
// Protobuf Java Version: 4.30.2

package io.github.seal90.serviceclient.carries.by.rsocket.context;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
