spring.application.name=http-server-webclient
seal.spring.service-client.http.forward-metadata[0]=overlay-ns
logging.level.root= INFO
# Enable Debug Logging for WebFlux Core and Codecs
logging.level.org.springframework.web.reactive= DEBUG
logging.level.org.springframework.http.codec= DEBUG
spring.rsocket.server.port=20001