spring:
  application:
    name: http-client-webclient

server:
  port: 8081

seal:
  spring:
    service-client:
      http:
        default-channel-name: "default-channel-name"
        channels:
          http-server-webclient-channel:
            address: "http://127.0.0.1:8080"
        services:
          http-server-webclient:
            channel-name: http-server-webclient-channel